logging:
  level:
    liquibase: DEBUG
    #org.springframework.r2dbc: DEBUG

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000

spring:
  application:
    name: hermes-core
    version: 0.0.1
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/hermes
    user: admin
    password: admin123
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/hermes
    username: admin
    password: admin123
  data:
    mongodb:
      database: hermes
      host: localhost
      port: 27017
      uri: mongodb://admin:admin123@localhost:27017/hermes?authSource=admin
    redis:
      url: redis://localhost:6379
      host: localhost
      password: session
      port: 6379
      repositories:
        enabled: false
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    generate-ddl: off
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#        globally_quoted_identifiers: true
  main:
    allow-bean-definition-overriding: true
